# Generated by Django 2.2 on 2020-05-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='slug',
        ),
    ]
