# Generated by Django 2.2 on 2020-05-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_remove_restaurantlocation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
