# Generated by Django 2.2 on 2020-05-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_auto_20200507_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantlocation',
            options={'ordering': ['-updated', '-timestamp']},
        ),
    ]
