# Generated by Django 3.2 on 2021-05-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0003_restaurants_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='RestaurantLocation',
        ),
    ]
