# Generated by Django 3.2 on 2021-05-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0007_auto_20210503_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='image',
            field=models.ImageField(default='image', upload_to='restaurant_logo'),
            preserve_default=False,
        ),
    ]
